sudo: required
dist: xenial
language: python
python:
- "3.7"
services:
- docker

matrix:
  fast_finish: true

# command to install dependencies
install:
- "nvm install 11"
- "npm install -g webpack-cli"
- "npm install -g webpack"
- "npm install --prefix ./shuffleboard2js/html/ --no-save"
- "pip install pyinstaller"

# command to create build 
script:
- "npm run --prefix ./shuffleboard2js/html/ build:prod"
- ./build_exe.sh
- "mv ./dist ./dist-windows"

deploy:
- provider: pypi
  skip_cleanup: true
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: sdist bdist_wheel
  on:
    tags: true

- provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist-windows/shuffleboard2js*.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never